repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.0
    hooks:
      # Run the linter.
      - id: ruff
        # TODO: remove ignore when ready
        args: ['--fix', '.', '--ignore', 'F841,E712']
      # Run the formatter.
      - id: ruff-format
        args: ['.']
