repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5  # Use the latest stable version
    hooks:
      # Run the linter.
      - id: ruff
        # TODO: remove ignore when ready
        args: ['--fix', '.', '--ignore', 'E501,B006,B008,SIM117']
      # Run the formatter.
      - id: ruff-format
        args: ['.']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
