services:
  # FastAPI app
  partyup:
    build: .
    container_name: partyup
    expose:
      - 8000
    command: "uv run uvicorn --host 0.0.0.0 ---port 8000 --workers $(nproc) --loop uvloop --http httptools --timeout-keep-alive 5 --log-level warning"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URI=postgresql+asyncpg://postgres:password@partyup_db:5432/partyup_db
      - ES_URI=http://elasticsearch:9200
      # - SECRET_KEY
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_SECONDS=86400
    depends_on:
      - partyup_db
      - redis
      - prometheus
      - elasticsearch
      - traefik
      - kibana
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.partyup.rule=Host(`partyup.localhost`)"
      - "traefik.http.routers.partyup.entrypoints=web"
      - "traefik.http.routers.partyup.middlewares=ratelimit@docker"
      - "traefik.http.middlewares.ratelimit.ratelimit.average=5"
      - "traefik.http.middlewares.ratelimit.ratelimit.burst=10"
      - "traefik.http.middlewares.ratelimit.ratelimit.period=1s"
      - "traefik.http.services.partyup.loadbalancer.server.port=8000"

  # PostgreSQL database
  partyup_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: partyup_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - partyup_db_data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  # Redis cache
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    labels:
      - "traefik.enable=false"

  # Prometheus + Grafana monitoring
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - app-network
    labels:
      - "traefik.enable=false"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
    labels:
      - "traefik.enable=false"

  # CloudBeaver for DB access
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - app-network
    labels:
      - "traefik.enable=false"

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network
    labels:
      - "traefik.enable=false"

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - app-network
    labels:
      - "traefik.enable=false"

  # Traefik reverse proxy
  traefik:
    image: traefik:v2.11
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - "traefik.enable=false"
    networks:
      - app-network

networks:
  app-network:

volumes:
  partyup_db_data:
  cloudbeaver:
