steps:
  - name: python:3.11-slim
    id: "setup-deps"
    entrypoint: bash
    args:
      - -c
      - |
        cd ../..
        pip install uv
        uv sync --frozen
        uv run pytest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: "deploy-function"
    entrypoint: gcloud
    args:
      [
        "functions", "deploy", "daily-payments-consumer",
        "--runtime", "python311",
        "--region", "europe-west1",
        "--source", "../..",
        "--entry-point", "consumers.workers.main.handle_pubsub_message",
        "--trigger-topic", "daily-payments-topic"
      ]

timeout: 1200s
