global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'partyup'
    static_configs:
      - targets: ['partyup:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
